name: genre_classification_prod
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.5.0
  - hydra-core=1.0.6
  - pip:
      - wandb==0.15.5
      - hydra-joblib-launcher==1.1.2
      - protobuf==3.20.*
